In [1]:
import pandas as pd

In [2]:
d = {
    'HCP_ID':['a1','a1','a1','a1','a1','a1','a1',
             'a2','a2','a2','a2','a2','a2','a2',
             'a3','a3','a3','a3','a3','a3','a3'],
    'Send_date':['2022-06-02','2022-06-04','2022-06-07','2022-06-20','2022-06-22','2022-06-28','2022-07-01',
                '2022-06-02','2022-06-04','2022-06-07','2022-06-20','2022-06-22','2022-06-28','2022-07-01',
                '2022-06-02','2022-06-04','2022-06-07','2022-06-20','2022-06-22','2022-06-28','2022-07-01'],
    'Channel':['F2F','Viber','Online','F2F','Email','Email','F2F',
              'Viber','Viber','Online','F2F','Email','Offline','F2F',
               'F2F','Viber','Online','F2F','Email','Email','F2F']
}

# Creating a DataFrame
df = pd.DataFrame(d)
df

   HCP_ID   Send_date  Channel
0      a1  2022-06-02      F2F
1      a1  2022-06-04    Viber
2      a1  2022-06-07   Online
3      a1  2022-06-20      F2F
4      a1  2022-06-22    Email
5      a1  2022-06-28    Email
6      a1  2022-07-01      F2F
7      a2  2022-06-02    Viber
8      a2  2022-06-04    Viber
9      a2  2022-06-07   Online
10     a2  2022-06-20      F2F
11     a2  2022-06-22    Email
12     a2  2022-06-28  Offline
13     a2  2022-07-01      F2F
14     a3  2022-06-02      F2F
15     a3  2022-06-04    Viber
16     a3  2022-06-07   Online
17     a3  2022-06-20      F2F
18     a3  2022-06-22    Email
19     a3  2022-06-28    Email
20     a3  2022-07-01      F2F

In [3]:
list(df.HCP_ID.unique())

['a1', 'a2', 'a3']

In [4]:
df_final=pd.DataFrame()
for i in list(df.HCP_ID.unique()):
    df_int=pd.DataFrame()
    
    ##Taking communication details of 1 HCP at a time in df_int
    df_int=df[df.HCP_ID==i]
    df_int=df_int.reset_index()
    df_int.drop(['index'],axis=1,inplace=True)
    
    #Create a column to store the immediate next communication channel for that HCP
    df_int['immediate_next_channel']=df_int['Channel'].shift(-1)
    
    #Immediate bect channel for the last communication is set as final communication
    df_int.immediate_next_channel=df_int.immediate_next_channel.fillna('Final_Communication')
    
    #Creating a df_final where we will store details of all HCP
    df_final=pd.concat([df_final,df_int],axis=0)
    df_final=df_final.reset_index()
    df_final.drop(['index'],axis=1,inplace=True)

In [5]:
df_final

   HCP_ID   Send_date  Channel immediate_next_channel
0      a1  2022-06-02      F2F                  Viber
1      a1  2022-06-04    Viber                 Online
2      a1  2022-06-07   Online                    F2F
3      a1  2022-06-20      F2F                  Email
4      a1  2022-06-22    Email                  Email
5      a1  2022-06-28    Email                    F2F
6      a1  2022-07-01      F2F    Final_Communication
7      a2  2022-06-02    Viber                  Viber
8      a2  2022-06-04    Viber                 Online
9      a2  2022-06-07   Online                    F2F
10     a2  2022-06-20      F2F                  Email
11     a2  2022-06-22    Email                Offline
12     a2  2022-06-28  Offline                    F2F
13     a2  2022-07-01      F2F    Final_Communication
14     a3  2022-06-02      F2F                  Viber
15     a3  2022-06-04    Viber                 Online
16     a3  2022-06-07   Online                    F2F
17     a3  2022-06-20      F2F                  Email
18     a3  2022-06-22    Email                  Email
19     a3  2022-06-28    Email                    F2F
20     a3  2022-07-01      F2F    Final_Communication

In [6]:
df_1=pd.get_dummies(df_final.immediate_next_channel)
df_1

    Email  F2F  Final_Communication  Offline  Online  Viber
0       0    0                    0        0       0      1
1       0    0                    0        0       1      0
2       0    1                    0        0       0      0
3       1    0                    0        0       0      0
4       1    0                    0        0       0      0
5       0    1                    0        0       0      0
6       0    0                    1        0       0      0
7       0    0                    0        0       0      1
8       0    0                    0        0       1      0
9       0    1                    0        0       0      0
10      1    0                    0        0       0      0
11      0    0                    0        1       0      0
12      0    1                    0        0       0      0
13      0    0                    1        0       0      0
14      0    0                    0        0       0      1
15      0    0                    0        0       1      0
16      0    1                    0        0       0      0
17      1    0                    0        0       0      0
18      1    0                    0        0       0      0
19      0    1                    0        0       0      0
20      0    0                    1        0       0      0

In [7]:
df_final=pd.concat([df_final,df_1],axis=1)
df_final

,HCP_ID,Send_date,Channel,immediate_next_channel,Email,F2F,Final_Communication,Offline,Online,Viber
0,a1,2022-06-02,F2F,Viber,0,0,0,0,0,1
1,a1,2022-06-04,Viber,Online,0,0,0,0,1,0
2,a1,2022-06-07,Online,F2F,0,1,0,0,0,0
3,a1,2022-06-20,F2F,Email,1,0,0,0,0,0
4,a1,2022-06-22,Email,Email,1,0,0,0,0,0
5,a1,2022-06-28,Email,F2F,0,1,0,0,0,0
6,a1,2022-07-01,F2F,Final_Communication,0,0,1,0,0,0
7,a2,2022-06-02,Viber,Viber,0,0,0,0,0,1
8,a2,2022-06-04,Viber,Online,0,0,0,0,1,0
9,a2,2022-06-07,Online,F2F,0,1,0,0,0,0
10,a2,2022-06-20,F2F,Email,1,0,0,0,0,0
11,a2,2022-06-22,Email,Offline,0,0,0,1,0,0
12,a2,2022-06-28,Offline,F2F,0,1,0,0,0,0
13,a2,2022-07-01,F2F,Final_Communication,0,0,1,0,0,0
14,a3,2022-06-02,F2F,Viber,0,0,0,0,0,1
15,a3,2022-06-04,Viber,Online,0,0,0,0,1,0
16,a3,2022-06-07,Online,F2F,0,1,0,0,0,0
17,a3,2022-06-20,F2F,Email,1,0,0,0,0,0
18,a3,2022-06-22,Email,Email,1,0,0,0,0,0
19,a3,2022-06-28,Email,F2F,0,1,0,0,0,0
20,a3,2022-07-01,F2F,Final_Communication,0,0,1,0,0,0

In [13]:
df

   HCP_ID   Send_date  Channel
0      a1  2022-06-02      F2F
1      a1  2022-06-04    Viber
2      a1  2022-06-07   Online
3      a1  2022-06-20      F2F
4      a1  2022-06-22    Email
5      a1  2022-06-28    Email
6      a1  2022-07-01      F2F
7      a2  2022-06-02    Viber
8      a2  2022-06-04    Viber
9      a2  2022-06-07   Online
10     a2  2022-06-20      F2F
11     a2  2022-06-22    Email
12     a2  2022-06-28  Offline
13     a2  2022-07-01      F2F